run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
